# First Imports

In [1]:
import os
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

In [ ]:

bikedata_2018_01 = pd.read_csv("./data/201801_capitalbikeshare_tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2017_q1 = pd.read_csv("./data/2017Q1-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2017_q2 = pd.read_csv("./data/2017Q2-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2017_q3 = pd.read_csv("./data/2017Q3-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2017_q4 = pd.read_csv("./data/2017Q4-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")

# 2018

## 2018 1-6

In [9]:
# Import dfs
 
bikedata_2018_01 = pd.read_csv("./data/201801_capitalbikeshare_tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_02 = pd.read_csv("./data/201802-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_03 = pd.read_csv("./data/201803-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_04 = pd.read_csv("./data/201804-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_05 = pd.read_csv("./data/201805-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_06 = pd.read_csv("./data/201806-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
 
# See df shapes and schemas

print('-----------2018-01-----------')
print(bikedata_2018_01.shape)
print(bikedata_2018_01.dtypes)
print('-----------2018-02-----------')
print(bikedata_2018_02.shape)
print(bikedata_2018_02.dtypes)
print('-----------2018-03-----------')
print(bikedata_2018_03.shape)
print(bikedata_2018_03.dtypes)
print('-----------2018-04-----------')
print(bikedata_2018_04.shape)
print(bikedata_2018_04.dtypes)
print('-----------2018-05-----------')
print(bikedata_2018_05.shape)
print(bikedata_2018_05.dtypes)
print('-----------2018-06-----------')
print(bikedata_2018_06.shape)
print(bikedata_2018_06.dtypes)

-----------2018-01-----------
(168590, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-02-----------
(182378, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-03-----------
(238998, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-04-----------
(328907, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-05-----------
(374115, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-06-----------
(392338, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object

In [17]:
# Empty the dataframes

bikedata_2018_01 = pd.DataFrame()
bikedata_2018_02 = pd.DataFrame()
bikedata_2018_03 = pd.DataFrame()
bikedata_2018_04 = pd.DataFrame()
bikedata_2018_05 = pd.DataFrame()
bikedata_2018_06 = pd.DataFrame()

## 2018 7-12

In [12]:
# Import dfs

bikedata_2018_07 = pd.read_csv("./data/201807-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_08 = pd.read_csv("./data/201808-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_09 = pd.read_csv("./data/201809-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_10 = pd.read_csv("./data/201810-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_11 = pd.read_csv("./data/201811-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_12 = pd.read_csv("./data/201812-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")


# See df shapes and schemas

print('-----------2018-07-----------')
print(bikedata_2018_07.shape)
print(bikedata_2018_07.dtypes)
print('-----------2018-08-----------')
print(bikedata_2018_08.shape)
print(bikedata_2018_08.dtypes)
print('-----------2018-09-----------')
print(bikedata_2018_09.shape)
print(bikedata_2018_09.dtypes)
print('-----------2018-10-----------')
print(bikedata_2018_10.shape)
print(bikedata_2018_10.dtypes)
print('-----------2018-11-----------')
print(bikedata_2018_11.shape)
print(bikedata_2018_11.dtypes)
print('-----------2018-12-----------')
print(bikedata_2018_12.shape)
print(bikedata_2018_12.dtypes)

-----------2018-07-----------
(404761, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-08-----------
(403866, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-09-----------
(325800, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-10-----------
(343021, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-11-----------
(221057, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2018-12-----------
(158853, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object

In [13]:
# Empty the dataframes

bikedata_2018_07 = pd.DataFrame()
bikedata_2018_08 = pd.DataFrame()
bikedata_2018_09 = pd.DataFrame()
bikedata_2018_10 = pd.DataFrame()
bikedata_2018_11 = pd.DataFrame()
bikedata_2018_12 = pd.DataFrame()

# 2019

## 2019 1-6

In [14]:
## 2019 1-6

# Import dfs

bikedata_2019_01 = pd.read_csv("./data/201901-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_02 = pd.read_csv("./data/201902-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_03 = pd.read_csv("./data/201903-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_04 = pd.read_csv("./data/201904-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_05 = pd.read_csv("./data/201905-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_06 = pd.read_csv("./data/201906-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")

# See df shapes and schemas

print('-----------2019-01-----------')
print(bikedata_2019_01.shape)
print(bikedata_2019_01.dtypes)
print('-----------2019-02-----------')
print(bikedata_2019_02.shape)
print(bikedata_2019_02.dtypes)
print('-----------2019-03-----------')
print(bikedata_2019_03.shape)
print(bikedata_2019_03.dtypes)
print('-----------2019-04-----------')
print(bikedata_2019_04.shape)
print(bikedata_2019_04.dtypes)
print('-----------2019-05-----------')
print(bikedata_2019_05.shape)
print(bikedata_2019_05.dtypes)
print('-----------2019-06-----------')
print(bikedata_2019_06.shape)
print(bikedata_2019_06.dtypes)

-----------2019-01-----------
(150780, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-02-----------
(158130, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-03-----------
(253811, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-04-----------
(347992, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-05-----------
(337704, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-06-----------
(350144, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object

In [18]:
# Empty the dataframes

bikedata_2019_01 = pd.DataFrame()
bikedata_2019_02 = pd.DataFrame()
bikedata_2019_03 = pd.DataFrame()
bikedata_2019_04 = pd.DataFrame()
bikedata_2019_05 = pd.DataFrame()
bikedata_2019_06 = pd.DataFrame()

## 2019 7-12

In [19]:
# Import dfs


bikedata_2019_07 = pd.read_csv("./data/201907-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_08 = pd.read_csv("./data/201908-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_09 = pd.read_csv("./data/201909-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_10 = pd.read_csv("./data/201910-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_11 = pd.read_csv("./data/201911-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_12 = pd.read_csv("./data/201912-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")

# See df shapes and schemas

print('-----------2019-07-----------')
print(bikedata_2019_07.shape)
print(bikedata_2019_07.dtypes)
print('-----------2019-08-----------')
print(bikedata_2019_08.shape)
print(bikedata_2019_08.dtypes)
print('-----------2019-09-----------')
print(bikedata_2019_09.shape)
print(bikedata_2019_09.dtypes)
print('-----------2019-10-----------')
print(bikedata_2019_10.shape)
print(bikedata_2019_10.dtypes)
print('-----------2019-11-----------')
print(bikedata_2019_11.shape)
print(bikedata_2019_11.dtypes)
print('-----------2019-12-----------')
print(bikedata_2019_12.shape)
print(bikedata_2019_12.dtypes)

-----------2019-06-----------
(350144, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-07-----------
(356645, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-08-----------
(360044, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-09-----------
(360225, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-10-----------
(337552, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-11-----------
(223512, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2019-12-----------
(161878, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object

In [ ]:
# Empty the dataframes

bikedata_2019_07 = pd.DataFrame()
bikedata_2019_08 = pd.DataFrame()
bikedata_2019_09 = pd.DataFrame()
bikedata_2019_10 = pd.DataFrame()
bikedata_2019_11 = pd.DataFrame()
bikedata_2019_12 = pd.DataFrame()

# 2020

Change in format happens at 2020-04 !

## 2020 1-6

In [20]:
# give me the same code for 2020 1 to 6

# Import dfs

bikedata_2020_01 = pd.read_csv("./data/202001-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_02 = pd.read_csv("./data/202002-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_03 = pd.read_csv("./data/202003-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_04 = pd.read_csv("./data/202004-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_05 = pd.read_csv("./data/202005-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_06 = pd.read_csv("./data/202006-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")

# See df shapes and schemas

print('-----------2020-01-----------')
print(bikedata_2020_01.shape)
print(bikedata_2020_01.dtypes)
print('-----------2020-02-----------')
print(bikedata_2020_02.shape)
print(bikedata_2020_02.dtypes)
print('-----------2020-03-----------')
print(bikedata_2020_03.shape)
print(bikedata_2020_03.dtypes)
print('-----------2020-04-----------')
print(bikedata_2020_04.shape)
print(bikedata_2020_04.dtypes)
print('-----------2020-05-----------')
print(bikedata_2020_05.shape)
print(bikedata_2020_05.dtypes)
print('-----------2020-06-----------')
print(bikedata_2020_06.shape)
print(bikedata_2020_06.dtypes)

-----------2020-01-----------
(196969, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2020-02-----------
(177901, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2020-03-----------
(162530, 9)
Duration                 int64
Start date              object
End date                object
Start station number     int64
Start station           object
End station number       int64
End station             object
Bike number             object
Member type             object
dtype: object
-----------2020-04-----------
(75471, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id        int64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2020-05-----------
(149051, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id        int64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2020-06-----------
(214047, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [21]:
# Empty these last 6 dataframes

bikedata_2020_01 = pd.DataFrame()
bikedata_2020_02 = pd.DataFrame()
bikedata_2020_03 = pd.DataFrame()
bikedata_2020_04 = pd.DataFrame()
bikedata_2020_05 = pd.DataFrame()
bikedata_2020_06 = pd.DataFrame()

## 2020 7-12

In [22]:
# give me the same code for 2020  7to12, for reading the files and then printing their shapes and dtypes in the same way as before

# Import dfs

bikedata_2020_07 = pd.read_csv("./data/202007-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_08 = pd.read_csv("./data/202008-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_09 = pd.read_csv("./data/202009-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_10 = pd.read_csv("./data/202010-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_11 = pd.read_csv("./data/202011-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2020_12 = pd.read_csv("./data/202012-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")

# See df shapes and schemas

print('-----------2020-07-----------')
print(bikedata_2020_07.shape)
print(bikedata_2020_07.dtypes)
print('-----------2020-08-----------')
print(bikedata_2020_08.shape)
print(bikedata_2020_08.dtypes)
print('-----------2020-09-----------')
print(bikedata_2020_09.shape)
print(bikedata_2020_09.dtypes)
print('-----------2020-10-----------')
print(bikedata_2020_10.shape)
print(bikedata_2020_10.dtypes)
print('-----------2020-11-----------')
print(bikedata_2020_11.shape)
print(bikedata_2020_11.dtypes)
print('-----------2020-12-----------')
print(bikedata_2020_12.shape)
print(bikedata_2020_12.dtypes)

-----------2020-07-----------
(228347, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2020-08-----------
(251603, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2020-09-----------
(249899, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2020-10-----------
(229832, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2020-11-----------
(175435, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2020-12-----------
(105829, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [23]:
# Empty these last 6 dataframes

bikedata_2020_07 = pd.DataFrame()
bikedata_2020_08 = pd.DataFrame()
bikedata_2020_09 = pd.DataFrame()
bikedata_2020_10 = pd.DataFrame()
bikedata_2020_11 = pd.DataFrame()
bikedata_2020_12 = pd.DataFrame()

# 2021

## 2021 1-6

In [24]:
# give me the same code for 2021 1to6 , for reading the files and then printing their shapes and dtypes in the same way as before

# Import dfs

bikedata_2021_01 = pd.read_csv("./data/202101-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_02 = pd.read_csv("./data/202102-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_03 = pd.read_csv("./data/202103-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_04 = pd.read_csv("./data/202104-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_05 = pd.read_csv("./data/202105-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_06 = pd.read_csv("./data/202106-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")

# See df shapes and schemas

print('-----------2021-01-----------')
print(bikedata_2021_01.shape)
print(bikedata_2021_01.dtypes)
print('-----------2021-02-----------')
print(bikedata_2021_02.shape)
print(bikedata_2021_02.dtypes)
print('-----------2021-03-----------')
print(bikedata_2021_03.shape)
print(bikedata_2021_03.dtypes)
print('-----------2021-04-----------')
print(bikedata_2021_04.shape)
print(bikedata_2021_04.dtypes)
print('-----------2021-05-----------')
print(bikedata_2021_05.shape)
print(bikedata_2021_05.dtypes)
print('-----------2021-06-----------')
print(bikedata_2021_06.shape)
print(bikedata_2021_06.dtypes)

/var/folders/94/tzvv8rm52074vxw9xhs1_2cm0000gn/T/ipykernel_1002/1412962375.py:6: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bikedata_2021_02 = pd.read_csv("./data/202102-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")

-----------2021-01-----------
(100070, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-02-----------
(77505, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-03-----------
(171165, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-04-----------
(216763, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-05-----------
(254177, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-06-----------
(275380, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [25]:
# Empty these last 6 dataframes

bikedata_2021_01 = pd.DataFrame()
bikedata_2021_02 = pd.DataFrame()
bikedata_2021_03 = pd.DataFrame()
bikedata_2021_04 = pd.DataFrame()
bikedata_2021_05 = pd.DataFrame()
bikedata_2021_06 = pd.DataFrame()

## 2021 7-12

In [26]:
# give me the same code for 2021  7to12, for reading the files and then printing their shapes and dtypes in the same way as before

# Import dfs

bikedata_2021_07 = pd.read_csv("./data/202107-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_08 = pd.read_csv("./data/202108-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_09 = pd.read_csv("./data/202109-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_10 = pd.read_csv("./data/202110-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_11 = pd.read_csv("./data/202111-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2021_12 = pd.read_csv("./data/202112-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")

# See df shapes and schemas

print('-----------2021-07-----------')
print(bikedata_2021_07.shape)
print(bikedata_2021_07.dtypes)
print('-----------2021-08-----------')
print(bikedata_2021_08.shape)
print(bikedata_2021_08.dtypes)
print('-----------2021-09-----------')
print(bikedata_2021_09.shape)
print(bikedata_2021_09.dtypes)
print('-----------2021-10-----------')
print(bikedata_2021_10.shape)
print(bikedata_2021_10.dtypes)
print('-----------2021-11-----------')
print(bikedata_2021_11.shape)
print(bikedata_2021_11.dtypes)
print('-----------2021-12-----------')
print(bikedata_2021_12.shape)
print(bikedata_2021_12.dtypes)

-----------2021-07-----------
(312426, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-08-----------
(271994, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-09-----------
(309197, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-10-----------
(328300, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-11-----------
(242057, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2021-12-----------
(190847, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [27]:
# Empty these last 6 dataframes

bikedata_2021_07 = pd.DataFrame()
bikedata_2021_08 = pd.DataFrame()
bikedata_2021_09 = pd.DataFrame()
bikedata_2021_10 = pd.DataFrame()
bikedata_2021_11 = pd.DataFrame()
bikedata_2021_12 = pd.DataFrame()

# 2022

## 2022 1-6

In [28]:
# give me the same code for 2022 1to6 , for reading the files and then printing their shapes and dtypes in the same way as before

# Import dfs

bikedata_2022_01 = pd.read_csv("./data/202201-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_02 = pd.read_csv("./data/202202-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_03 = pd.read_csv("./data/202203-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_04 = pd.read_csv("./data/202204-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_05 = pd.read_csv("./data/202205-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_06 = pd.read_csv("./data/202206-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")

# See df shapes and schemas

print('-----------2022-01-----------')
print(bikedata_2022_01.shape)
print(bikedata_2022_01.dtypes)
print('-----------2022-02-----------')
print(bikedata_2022_02.shape)
print(bikedata_2022_02.dtypes)
print('-----------2022-03-----------')
print(bikedata_2022_03.shape)
print(bikedata_2022_03.dtypes)
print('-----------2022-04-----------')
print(bikedata_2022_04.shape)
print(bikedata_2022_04.dtypes)
print('-----------2022-05-----------')
print(bikedata_2022_05.shape)
print(bikedata_2022_05.dtypes)
print('-----------2022-06-----------')
print(bikedata_2022_06.shape)
print(bikedata_2022_06.dtypes)

-----------2022-01-----------
(109619, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-02-----------
(154317, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-03-----------
(254250, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-04-----------
(310435, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-05-----------
(332821, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-06-----------
(389656, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [29]:
# Empty these last 6 dataframes

# Empty these last 6 dataframes

bikedata_2022_01 = pd.DataFrame()
bikedata_2022_02 = pd.DataFrame()
bikedata_2022_03 = pd.DataFrame()
bikedata_2022_04 = pd.DataFrame()
bikedata_2022_05 = pd.DataFrame()
bikedata_2022_06 = pd.DataFrame()

## 2022 7-12

In [30]:
# give me the same code for 2022 7to12 , for reading the files and then printing their shapes and dtypes in the same way as before

# Import dfs

bikedata_2022_07 = pd.read_csv("./data/202207-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_08 = pd.read_csv("./data/202208-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_09 = pd.read_csv("./data/202209-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_10 = pd.read_csv("./data/202210-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_11 = pd.read_csv("./data/202211-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2022_12 = pd.read_csv("./data/202212-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")

# See df shapes and schemas

print('-----------2022-07-----------')
print(bikedata_2022_07.shape)
print(bikedata_2022_07.dtypes)
print('-----------2022-08-----------')
print(bikedata_2022_08.shape)
print(bikedata_2022_08.dtypes)
print('-----------2022-09-----------')
print(bikedata_2022_09.shape)
print(bikedata_2022_09.dtypes)
print('-----------2022-10-----------')
print(bikedata_2022_10.shape)
print(bikedata_2022_10.dtypes)
print('-----------2022-11-----------')
print(bikedata_2022_11.shape)
print(bikedata_2022_11.dtypes)
print('-----------2022-12-----------')
print(bikedata_2022_12.shape)
print(bikedata_2022_12.dtypes)

-----------2022-07-----------
(393683, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-08-----------
(377657, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-09-----------
(386085, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-10-----------
(333309, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-11-----------
(259717, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2022-12-----------
(175233, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [31]:
# Empty these last 6 dataframes

bikedata_2022_07 = pd.DataFrame()
bikedata_2022_08 = pd.DataFrame()
bikedata_2022_09 = pd.DataFrame()
bikedata_2022_10 = pd.DataFrame()
bikedata_2022_11 = pd.DataFrame()
bikedata_2022_12 = pd.DataFrame()

# 2023

## 2023 1-6

In this range I found a file that had been incorrectly downloaded and was causing problems, which is why I had to break the code into smaller portions to find the problem.

In [3]:
# give me the same code for 2023 1to6 , for reading the files and then printing their shapes and dtypes in the same way as before

# Import dfs

bikedata_2023_01 = pd.read_csv("./data/202301-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2023_02 = pd.read_csv("./data/202302-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")
bikedata_2023_03 = pd.read_csv("./data/202303-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")


# See df shapes and schemas

print('-----------2023-01-----------')
print(bikedata_2023_01.shape)
print(bikedata_2023_01.dtypes)
print('-----------2023-02-----------')
print(bikedata_2023_02.shape)
print(bikedata_2023_02.dtypes)
print('-----------2023-03-----------')
print(bikedata_2023_03.shape)
print(bikedata_2023_03.dtypes)

-----------2023-01-----------
(204077, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2023-02-----------
(207591, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object
-----------2023-03-----------
(290430, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [5]:
# Import dfs

bikedata_2023_04 = pd.read_csv("./data/202304-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")


# See df shapes and schemas

print('-----------2023-04-----------')
print(bikedata_2023_04.shape)
print(bikedata_2023_04.dtypes)

-----------2023-04-----------
(389243, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [6]:
# Import dfs

bikedata_2023_05 = pd.read_csv("./data/202305-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")


# See df shapes and schemas


print('-----------2023-05-----------')
print(bikedata_2023_05.shape)
print(bikedata_2023_05.dtypes)

-----------2023-05-----------
(431952, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [2]:
# This is the difficult file

# Import dfs

bikedata_2023_06 = pd.read_csv("./data/202306-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")


# See df shapes and schemas

print('-----------2023-06-----------')
print(bikedata_2023_06.shape)
print(bikedata_2023_06.dtypes)

-----------2023-06-----------
(430670, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [3]:
# Empty these last 6 dataframes

bikedata_2023_01 = pd.DataFrame()
bikedata_2023_02 = pd.DataFrame()
bikedata_2023_03 = pd.DataFrame()
bikedata_2023_04 = pd.DataFrame()
bikedata_2023_05 = pd.DataFrame()
bikedata_2023_06 = pd.DataFrame()

## 2023 7-9

In [5]:
# give me the same code for 2023  7to12, for reading the files and then printing their shapes and dtypes in the same way as before

# Import dfs

bikedata_2023_07 = pd.read_csv("./data/202307-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")

# See df shapes and schemas

print('-----------2023-07-----------')
print(bikedata_2023_07.shape)
print(bikedata_2023_07.dtypes)

-----------2023-07-----------
(466422, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [8]:
# Another corrrupted file error


# Import dfs

bikedata_2023_08 = pd.read_csv("./data/202308-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")


# See df shapes and schemas

print('-----------2023-08-----------')
print(bikedata_2023_08.shape)
print(bikedata_2023_08.dtypes)

-----------2023-08-----------
(470132, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [9]:
# Another corrrupted file error

# Import dfs

bikedata_2023_09 = pd.read_csv("./data/202309-capitalbikeshare-tripdata.csv", sep=",", decimal=".", encoding="latin1")


# See df shapes and schemas

print('-----------2023-09-----------')
print(bikedata_2023_09.shape)
print(bikedata_2023_09.dtypes)

-----------2023-09-----------
(450090, 13)
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id      float64
end_station_name       object
end_station_id        float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [10]:
# Empty these last 6 dataframes

# Empty these last 6 dataframes
bikedata_2023_07 = pd.DataFrame()
bikedata_2023_08 = pd.DataFrame()
bikedata_2023_09 = pd.DataFrame()

# REST

In [ ]:
# Import dfs

bikedata_2018_07 = pd.read_csv("./data/201807-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_08 = pd.read_csv("./data/201808-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_09 = pd.read_csv("./data/201809-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_10 = pd.read_csv("./data/201810-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_11 = pd.read_csv("./data/201811-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2018_12 = pd.read_csv("./data/201812-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")

In [10]:
bikedata_2018_11 = pd.read_csv("./data/201811-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_03 = pd.read_csv("./data/201903-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2019_06 = pd.read_csv("./data/201906-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2020_04 = pd.read_csv("./data/202004-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2020_10 = pd.read_csv("./data/202010-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2021_03 = pd.read_csv("./data/202103-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2022_07 = pd.read_csv("./data/202207-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")
bikedata_2023_03 = pd.read_csv("./data/202303-capitalbikeshare-tripdata.csv", sep=",", decimal=",", encoding="latin1")

# See df shapes and schemas

In [5]:
bikedata_2018_11.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,876,2018-11-01 00:00:45,2018-11-01 00:15:21,31237,25th St & Pennsylvania Ave NW,31604,3rd & H St NW,W00277,Member
1,308,2018-11-01 00:00:52,2018-11-01 00:06:00,32204,Tysons Corner Station,32229,Park Run & Onyx Dr,W22007,Casual
2,186,2018-11-01 00:01:46,2018-11-01 00:04:52,31611,13th & H St NE,31632,15th & F St NE,W01105,Member
3,988,2018-11-01 00:01:52,2018-11-01 00:18:20,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,31204,20th & E St NW,W21689,Casual
4,1454,2018-11-01 00:05:08,2018-11-01 00:29:23,31107,Lamont & Mt Pleasant NW,31509,New Jersey Ave & R St NW,W22586,Casual

In [6]:
bikedata_2019_03.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,896,2019-03-01 00:02:23,2019-03-01 00:17:19,31234,20th & O St NW / Dupont South,31306,39th & Calvert St NW / Stoddert,W01259,Member
1,613,2019-03-01 00:03:10,2019-03-01 00:13:23,31323,Woodley Park Metro / Calvert St & Connecticut ...,31214,17th & Corcoran St NW,W22263,Member
2,652,2019-03-01 00:04:14,2019-03-01 00:15:06,31651,11th & Park Rd NW,31506,1st & Rhode Island Ave NW,W00825,Member
3,676,2019-03-01 00:05:11,2019-03-01 00:16:27,31400,Georgia & New Hampshire Ave NW,31212,21st & M St NW,W24162,Member
4,587,2019-03-01 00:08:04,2019-03-01 00:17:51,31293,31st & Water St NW,31250,20th & L St NW,W21644,Member

In [7]:
bikedata_2020_04.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,77A0F1B26D1597B1,docked_bike,2020-04-25 17:28:39,2020-04-25 17:35:04,Rhode Island & Connecticut Ave NW,31239,12th & L St NW,31251.0,38.905995699991145,-77.03980207443237,38.903819,-77.0284,casual
1,8698F10128EA4F18,docked_bike,2020-04-06 07:54:59,2020-04-06 07:57:24,21st & I St NW,31205,18th & L St NW,31224.0,38.90071062547463,-77.04644858837128,38.903741450919384,-77.04245209693909,member
2,AA07819DC0F58872,docked_bike,2020-04-22 17:06:18,2020-04-22 18:08:32,Connecticut Ave & Tilden St NW,31313,Connecticut Ave & Tilden St NW,31313.0,38.94113915653008,-77.061977237463,38.94113915653008,-77.061977237463,casual
3,DA909BCA92EF85AB,docked_bike,2020-04-16 15:22:40,2020-04-16 15:58:37,7th & E St SW,31294,7th & E St SW,31294.0,38.88345,-77.021741,38.88345,-77.021741,casual
4,B36F1E14D8C6757E,docked_bike,2020-04-10 13:19:41,2020-04-10 13:23:05,Potomac & Pennsylvania Ave SE,31606,8th & Eye St SE / Barracks Row,31608.0,38.8803,-76.9862,38.8792,-76.9953,member

In [9]:
bikedata_2020_10.head(30)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,5160990A29898496,electric_bike,2020-10-12 07:38:42,2020-10-12 07:52:38,NaN,NaN,NaN,NaN,38.81,-77.06,38.84,-77.06,casual
1,AB3EDB59F4D802E7,electric_bike,2020-10-02 17:58:30,2020-10-02 18:07:45,NaN,NaN,NaN,NaN,38.93,-77.0,38.91,-77.0,casual
2,238A92D9D011475D,electric_bike,2020-10-02 00:13:37,2020-10-02 00:21:10,NaN,NaN,NaN,NaN,38.91,-77.04,38.9,-77.0,casual
3,59D6EF767F57C139,electric_bike,2020-10-02 16:31:12,2020-10-02 16:42:50,NaN,NaN,NaN,NaN,38.92,-77.03,38.91,-77.0,casual
4,A94B93E9E864972A,electric_bike,2020-10-19 21:33:46,2020-10-19 21:43:55,NaN,NaN,14th & V St NW,31101.0,38.91,-77.04,38.91769016666667,-77.03182133333334,casual
5,05407AA6EC505BB0,electric_bike,2020-10-02 22:36:37,2020-10-02 22:44:32,NaN,NaN,NaN,NaN,38.95,-77.08,38.93,-77.07,casual
6,E5337FFD1650425E,electric_bike,2020-10-03 18:18:32,2020-10-03 18:37:38,NaN,NaN,NaN,NaN,38.91,-77.05,38.93,-77.03,casual
7,7354B9BF1779C97B,electric_bike,2020-10-01 18:12:21,2020-10-01 18:27:38,NaN,NaN,NaN,NaN,38.91,-77.03,38.9,-77.0,casual
8,228ED0B6943E14C3,electric_bike,2020-10-01 07:06:02,2020-10-01 07:40:24,NaN,NaN,NaN,NaN,38.94,-76.97,38.92,-77.01,casual
9,6D078BF96CD03EC9,electric_bike,2020-10-15 12:15:19,2020-10-15 12:39:01,NaN,NaN,NaN,NaN,38.91,-77.02,38.9,-77.01,casual
10,AC20FF4787A4CF5F,electric_bike,2020-10-02 16:15:03,2020-10-02 16:17:42,NaN,NaN,NaN,NaN,38.87,-77.08,38.87,-77.07,casual
11,8DFCA464CAB194C1,electric_bike,2020-10-02 16:26:29,2020-10-02 16:41:08,NaN,NaN,NaN,NaN,38.91,-77.04,38.93,-77.03,casual
12,6F92F71EF7538246,electric_bike,2020-10-04 13:29:42,2020-10-04 14:01:20,NaN,NaN,NaN,NaN,38.93,-77.03,38.9,-76.99,casual
13,D346A087EE4C689B,electric_bike,2020-10-17 05:17:42,2020-10-17 05:30:45,NaN,NaN,NaN,NaN,38.94,-76.97,38.92,-77.0,casual
14,4E4E30B773ABA515,electric_bike,2020-10-12 18:17:43,2020-10-12 18:30:51,NaN,NaN,NaN,NaN,38.9,-77.05,38.9,-77.02,casual
15,F15AC55404A33698,electric_bike,2020-10-11 21:17:05,2020-10-11 21:19:45,NaN,NaN,NaN,NaN,38.84,-77.08,38.84,-77.08,casual
16,081015ACB2212C35,electric_bike,2020-10-11 21:30:11,2020-10-11 21:34:14,NaN,NaN,NaN,NaN,38.84,-77.08,38.84,-77.08,casual
17,49BBD3AA0DD0A6B8,electric_bike,2020-10-22 21:09:56,2020-10-22 21:13:51,NaN,NaN,NaN,NaN,38.84,-77.08,38.84,-77.08,casual
18,AF5586192575CAE8,electric_bike,2020-10-23 18:35:17,2020-10-23 18:40:55,NaN,NaN,NaN,NaN,38.84,-77.08,38.84,-77.08,casual
19,6B435C2C3124E80F,electric_bike,2020-10-22 21:16:54,2020-10-22 21:38:10,NaN,NaN,NaN,NaN,38.84,-77.08,38.85,-77.05,casual
20,B377BAC437C3594E,electric_bike,2020-10-23 18:17:35,2020-10-23 18:30:21,NaN,NaN,NaN,NaN,38.84,-77.05,38.84,-77.08,casual
21,EDDA46FE75456A70,electric_bike,2020-10-22 22:20:20,2020-10-22 22:47:50,NaN,NaN,NaN,NaN,38.85,-77.05,38.84,-77.08,casual
22,49819CC53EFB0389,electric_bike,2020-10-23 16:49:27,2020-10-23 17:02:33,NaN,NaN,NaN,NaN,38.84,-77.08,38.84,-77.05,casual
23,3ACFBFD7BFC0DACF,electric_bike,2020-10-23 07:10:57,2020-10-23 08:23:57,NaN,NaN,NaN,NaN,38.91,-77.07,38.9,-77.08,casual
24,939C723BEAF488D9,electric_bike,2020-10-23 00:11:36,2020-10-23 01:21:48,NaN,NaN,NaN,NaN,38.94,-77.0,38.96,-77.03,casual
25,AFCF06E53986C846,electric_bike,2020-10-23 07:29:45,2020-10-23 07:34:53,NaN,NaN,NaN,NaN,38.93,-77.03,38.92,-77.04,casual
26,FE3D033A4BD40560,electric_bike,2020-10-28 17:17:47,2020-10-28 17:22:03,NaN,NaN,NaN,NaN,38.93,-77.03,38.94,-77.03,casual
27,06C438739CF6B950,electric_bike,2020-10-28 07:19:36,2020-10-28 07:25:55,NaN,NaN,NaN,NaN,38.93,-77.03,38.92,-77.04,casual
28,11B088328D6B5C59,electric_bike,2020-10-22 18:48:19,2020-10-22 18:59:47,NaN,NaN,NaN,NaN,38.9,-77.05,38.91,-77.05,casual
29,62B8863A4B346234,electric_bike,2020-10-13 23:03:20,2020-10-13 23:28:29,NaN,NaN,NaN,NaN,38.86,-77.08,38.88,-77.15,casual

In [11]:
bikedata_2021_03.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,8E20F5D0158AF914,classic_bike,2021-03-20 09:46:54,2021-03-20 09:55:14,Convention Center / 7th & M St NW,31223.0,3rd & Elm St NW,31118.0,38.905737,-77.02227,38.917622,-77.01597,member
1,7718672ECB745D5B,electric_bike,2021-03-12 16:37:17,2021-03-12 16:58:28,US Dept of State / Virginia Ave & 21st St NW,31220.0,Anacostia Roller Skating Pavillion,31720.0,38.89482116666667,-77.04658983333333,38.878772166666664,-76.97090583333333,member
2,CB8FD07893C27276,classic_bike,2021-03-13 12:38:15,2021-03-13 13:04:01,Towers Crescent Dr & Tysons One Pl,32222.0,Dunn Loring Metro,32231.0,38.915246,-77.220157,38.8828,-77.2283,casual
3,6C0C775AC0888E55,classic_bike,2021-03-16 17:01:00,2021-03-16 17:06:00,14th & D St SE,31663.0,11th & C St SE,31659.0,38.8840581,-76.9863852,38.885908,-76.991476,member
4,041B42F011BB5CCE,classic_bike,2021-03-31 12:49:33,2021-03-31 12:52:17,14th & D St SE,31663.0,11th & C St SE,31659.0,38.8840581,-76.9863852,38.885908,-76.991476,member

In [12]:
bikedata_2022_07.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,023A22990112155D,classic_bike,2022-07-29 18:44:37,2022-07-29 18:57:09,Fairfax Dr & N Randolph St,31034.0,Clarendon Blvd & Pierce St,31016.0,38.882629,-77.109366,38.893438,-77.076389,member
1,AB7451BFA95ADC66,classic_bike,2022-07-22 18:18:54,2022-07-22 18:24:36,Fern St & Army Navy Dr,31936.0,Crystal City Metro / 18th St & S Bell St,31007.0,38.864838,-77.056873,38.85778509815245,-77.05169767141342,member
2,F3301E3CA0A6F6EA,classic_bike,2022-07-23 13:40:54,2022-07-23 13:41:03,2nd & G St NE,31639.0,2nd & G St NE,31639.0,38.89967,-77.003666,38.89967,-77.003666,member
3,245EBE5294DD9136,classic_bike,2022-07-05 16:24:30,2022-07-05 16:24:52,USDA / 12th & C St SW,31217.0,USDA / 12th & C St SW,31217.0,38.88627694506511,-77.02824175357819,38.88627694506511,-77.02824175357819,member
4,4CBA79FC841A54D0,classic_bike,2022-07-02 15:16:50,2022-07-02 16:36:47,Harvard St & Adams Mill Rd NW,31112.0,Harvard St & Adams Mill Rd NW,31112.0,38.927872,-77.043358,38.927872,-77.043358,casual

In [13]:
bikedata_2023_03.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,20CAF4CAD9186B1C,docked_bike,2023-03-26 16:52:35,2023-03-26 17:22:08,Washington & Independence Ave SW/HHS,31272.0,15th St & Constitution Ave NW,31321.0,38.886978,-77.013769,38.892244,-77.033234,casual
1,695D9110D59A0A42,classic_bike,2023-03-28 16:51:30,2023-03-28 17:06:32,11th & C St SE,31659.0,D St & Maryland Ave NE,31612.0,38.885908,-76.991476,38.89484064247075,-76.99591577053069,member
2,3E284FFCC357FBEF,classic_bike,2023-03-28 19:25:55,2023-03-28 19:36:41,18th & M St NW,31221.0,California St & Florida Ave NW,31116.0,38.90506687455313,-77.04177886247635,38.917761,-77.04062,member
3,47CC92C4A31AB8CA,classic_bike,2023-03-03 16:33:58,2023-03-03 16:38:52,17th & K St NW,31213.0,17th & K St NW / Farragut Square,31233.0,38.90276,-77.03863,38.902061,-77.038322,member
4,A4B1F3F9E8DF03A3,docked_bike,2023-03-11 14:31:24,2023-03-11 14:54:06,10th & G St NW,31274.0,2nd St & Massachusetts Ave NE,31641.0,38.898243,-77.026235,38.894972,-77.003135,casual

In [4]:
print(bikedata_2018_01.shape)
print(bikedata_2017_q1.shape)
print(bikedata_2017_q2.shape)
print(bikedata_2017_q3.shape)
print(bikedata_2017_q4.shape)

(168590, 9)
(646510, 9)
(1104418, 9)
(1191585, 9)
(815264, 9)

In [5]:
bikedata_2018_01.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,552,2018-01-01 00:05:06,2018-01-01 00:14:18,31104,Adams Mill & Columbia Rd NW,31400,Georgia & New Hampshire Ave NW,W00886,Member
1,1282,2018-01-01 00:14:30,2018-01-01 00:35:53,31321,15th St & Constitution Ave NW,31321,15th St & Constitution Ave NW,W01435,Casual
2,1265,2018-01-01 00:14:53,2018-01-01 00:35:58,31321,15th St & Constitution Ave NW,31321,15th St & Constitution Ave NW,W21242,Casual
3,578,2018-01-01 00:15:31,2018-01-01 00:25:09,31406,14th & Upshur St NW,31103,16th & Harvard St NW,W21322,Casual
4,372,2018-01-01 00:18:02,2018-01-01 00:24:15,31618,4th & East Capitol St NE,31619,Lincoln Park / 13th & East Capitol St NE,W00119,Member

In [6]:
bikedata_2017_q1.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,221,2017-01-01 00:00:41,2017-01-01 00:04:23,31634,3rd & Tingey St SE,31208,M St & New Jersey Ave SE,W00869,Member
1,1676,2017-01-01 00:06:53,2017-01-01 00:34:49,31258,Lincoln Memorial,31270,8th & D St NW,W00894,Casual
2,1356,2017-01-01 00:07:10,2017-01-01 00:29:47,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,31222,New York Ave & 15th St NW,W21945,Casual
3,1327,2017-01-01 00:07:22,2017-01-01 00:29:30,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,31222,New York Ave & 15th St NW,W20012,Casual
4,1636,2017-01-01 00:07:36,2017-01-01 00:34:52,31258,Lincoln Memorial,31270,8th & D St NW,W22786,Casual

In [7]:
bikedata_2017_q2.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,381,2017-04-01 00:00:22,2017-04-01 00:06:43,31238,14th & G St NW,31202,14th & R St NW,W22257,Member
1,590,2017-04-01 00:02:02,2017-04-01 00:11:53,31109,7th & T St NW,31278,18th & R St NW,W20006,Member
2,2938,2017-04-01 00:02:32,2017-04-01 00:51:30,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,31238,14th & G St NW,W22225,Casual
3,380,2017-04-01 00:03:02,2017-04-01 00:09:23,31121,Calvert St & Woodley Pl NW,31104,Adams Mill & Columbia Rd NW,W20146,Member
4,423,2017-04-01 00:03:38,2017-04-01 00:10:41,31023,Fairfax Dr & Wilson Blvd,31034,N Randolph St & Fairfax Dr,W00316,Member

In [8]:
bikedata_2017_q3.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,2762,2017-07-01 00:01:09,2017-07-01 00:47:11,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,W21474,Casual
1,2763,2017-07-01 00:01:24,2017-07-01 00:47:27,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,W22042,Casual
2,690,2017-07-01 00:01:45,2017-07-01 00:13:16,31122,16th & Irving St NW,31299,Connecticut Ave & R St NW,W01182,Member
3,134,2017-07-01 00:01:46,2017-07-01 00:04:00,31201,15th & P St NW,31267,17th St & Massachusetts Ave NW,W22829,Member
4,587,2017-07-01 00:02:05,2017-07-01 00:11:52,31099,Madison & N Henry St,31907,Franklin & S Washington St,W22223,Casual

In [9]:
bikedata_2017_q4.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,197,2017-10-01 00:00:02,2017-10-01 00:03:19,31214,17th & Corcoran St NW,31229,New Hampshire Ave & T St NW,W21022,Member
1,434,2017-10-01 00:00:23,2017-10-01 00:07:38,31104,Adams Mill & Columbia Rd NW,31602,Park Rd & Holmead Pl NW,W00470,Member
2,955,2017-10-01 00:00:56,2017-10-01 00:16:52,31221,18th & M St NW,31103,16th & Harvard St NW,W20206,Member
3,461,2017-10-01 00:00:56,2017-10-01 00:08:37,31111,10th & U St NW,31102,11th & Kenyon St NW,W21014,Member
4,3357,2017-10-01 00:00:59,2017-10-01 00:56:56,31260,23rd & E St NW,31260,23rd & E St NW,W22349,Casual

In [10]:
# Print descriptive statistics for each dataset
print("Descriptive Statistics for 2018 January Data:")
print(bikedata_2018_01.describe(), "\n")

print("Descriptive Statistics for 2017 Q1 Data:")
print(bikedata_2017_q1.describe(), "\n")

print("Descriptive Statistics for 2017 Q2 Data:")
print(bikedata_2017_q2.describe(), "\n")

print("Descriptive Statistics for 2017 Q3 Data:")
print(bikedata_2017_q3.describe(), "\n")

print("Descriptive Statistics for 2017 Q4 Data:")
print(bikedata_2017_q4.describe(), "\n")

Descriptive Statistics for 2018 January Data:
            Duration  Start station number  End station number
count  168590.000000         168590.000000       168590.000000
mean      816.769530          31324.874702        31326.967163
std      1746.552062            225.491279          223.741510
min        60.000000          31000.000000        31000.000000
25%       336.000000          31201.000000        31203.000000
50%       554.000000          31256.000000        31255.000000
75%       917.000000          31510.000000        31511.000000
max     86372.000000          32225.000000        32225.000000

Descriptive Statistics for 2017 Q1 Data:
            Duration  Start station number  End station number
count  646510.000000         646510.000000       646510.000000
mean     1010.444949          31317.411972        31320.159818
std      2087.021859            218.034279          216.394175
min        60.000000          31000.000000        31000.000000
25%       373.000000          31202.000000        31207.000000
50%       626.000000          31251.000000        31250.000000
75%      1064.000000          31505.000000        31505.000000
max     86066.000000          32223.000000        32223.000000

Descriptive Statistics for 2017 Q2 Data:
           Duration  Start station number  End station number
count  1.104418e+06          1.104418e+06        1.104418e+06
mean   1.271559e+03          3.131847e+04        3.131869e+04
std    2.300466e+03          2.188014e+02        2.161327e+02
min    6.000000e+01          3.100000e+04        3.100000e+04
25%    4.370000e+02          3.120900e+04        3.121200e+04
50%    7.630000e+02          3.125400e+04        3.125200e+04
75%    1.324000e+03          3.140700e+04        3.140400e+04
max    8.637800e+04          3.222500e+04        3.222500e+04

Descriptive Statistics for 2017 Q3 Data:
           Duration  Start station number  End station number
count  1.191585e+06          1.191585e+06        1.191585e+06
mean   1.231104e+03          3.132080e+04        3.132111e+04
std    2.116393e+03          2.209040e+02        2.183471e+02
min    6.000000e+01          3.100000e+04        3.100000e+04
25%    4.360000e+02          3.120900e+04        3.121200e+04
50%    7.650000e+02          3.125700e+04        3.125600e+04
75%    1.322000e+03          3.140800e+04        3.140600e+04
max    8.639400e+04          3.222500e+04        3.222500e+04

Descriptive Statistics for 2017 Q4 Data:
            Duration  Start station number  End station number
count  815264.000000         815264.000000       815264.000000
mean      992.973769          31324.948151        31325.226031
std      1871.168848            224.697081          221.883506
min        60.000000          31000.000000        31000.000000
25%       380.000000          31203.000000        31207.000000
50%       644.000000          31257.000000        31256.000000
75%      1087.000000          31506.000000        31506.000000
max     86275.000000          32225.000000        32225.000000

In [11]:
# Print the number of unique values in each column for each dataset
print("Unique Values for 2018 January Data:")
print(bikedata_2018_01.nunique(), "\n")

print("Unique Values for 2017 Q1 Data:")
print(bikedata_2017_q1.nunique(), "\n")

print("Unique Values for 2017 Q2 Data:")
print(bikedata_2017_q2.nunique(), "\n")

print("Unique Values for 2017 Q3 Data:")
print(bikedata_2017_q3.nunique(), "\n")

print("Unique Values for 2017 Q4 Data:")
print(bikedata_2017_q4.nunique(), "\n")

Unique Values for 2018 January Data:
Duration                  5717
Start date              157143
End date                156928
Start station number       486
Start station              486
End station number         484
End station                484
Bike number               4021
Member type                  2
dtype: int64

Unique Values for 2017 Q1 Data:
Duration                 11648
Start date              591877
End date                592066
Start station number       452
Start station              452
End station number         452
End station                452
Bike number               4298
Member type                  2
dtype: int64

Unique Values for 2017 Q2 Data:
Duration                 15811
Start date              975664
End date                975332
Start station number       472
Start station              472
End station number         472
End station                472
Bike number               4348
Member type                  2
dtype: int64

Unique Values for 2017 Q3 Data:
Duration                  15260
Start date              1048019
End date                1047721
Start station number        482
Start station               482
End station number          483
End station                 483
Bike number                4067
Member type                   2
dtype: int64

Unique Values for 2017 Q4 Data:
Duration                 11828
Start date              735101
End date                734291
Start station number       486
Start station              486
End station number         486
End station                486
Bike number               4291
Member type                  2
dtype: int64

In [16]:
import plotly.graph_objects as go

# Exclude date columns
columns_to_exclude = ['Start date', 'End date', 'Duration']

unique_values = {
    '2018 January': bikedata_2018_01.nunique().drop(labels=columns_to_exclude),
    '2017 Q1': bikedata_2017_q1.nunique().drop(labels=columns_to_exclude),
    '2017 Q2': bikedata_2017_q2.nunique().drop(labels=columns_to_exclude),
    '2017 Q3': bikedata_2017_q3.nunique().drop(labels=columns_to_exclude),
    '2017 Q4': bikedata_2017_q4.nunique().drop(labels=columns_to_exclude)
}

datasets = ['2018 January', '2017 Q1', '2017 Q2', '2017 Q3', '2017 Q4']

# Creating the bar chart
fig = go.Figure()
for dataset in datasets:
    fig.add_trace(go.Bar(x=unique_values[dataset].index, y=unique_values[dataset].values, name=dataset))

fig.update_layout(
    title='Unique Values in Each Column by Dataset (Excluding Dates)',
    xaxis_title='Columns',
    yaxis_title='Number of Unique Values',
    barmode='group'
)
fig.show()